-- MySQL Script generated by MySQL Workbench
-- 04/20/17 20:30:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`billtoaddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`billtoaddress` (
  `Billtoaddress_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` INT(11) NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Customer_emailid` VARCHAR(45) NOT NULL,
  `Address1` VARCHAR(45) NULL DEFAULT NULL,
  `Address2` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `Mobilenumber` VARCHAR(50) NULL DEFAULT NULL,
  `Zipcode` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Billtoaddress_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `Cart_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cart_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cartitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartitems` (
  `CartItems_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Cart_id` INT(11) NOT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `Product_id` INT(11) NOT NULL,
  PRIMARY KEY (`CartItems_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `Category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Category_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Category_id`),
  UNIQUE INDEX `Category_id_UNIQUE` (`Category_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `Customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer__username` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_password` VARCHAR(15) NULL DEFAULT NULL,
  `Customer_emailid` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_firstname` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_lastname` VARCHAR(45) NULL DEFAULT NULL,
  `Customer_mobilenumber` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_id`),
  UNIQUE INDEX `Customer_id_UNIQUE` (`Customer_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `Customer_id` INT(11) NULL DEFAULT NULL,
  `Order_id` VARCHAR(45) NULL DEFAULT NULL,
  `LineItems_id` VARCHAR(45) NULL DEFAULT NULL,
  `Invoicecol` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`lineitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lineitems` (
  `LineItems_id` INT(11) NOT NULL,
  `Product_id` INT(11) NULL DEFAULT NULL,
  `Product_name` VARCHAR(45) NULL DEFAULT NULL,
  `Product_desc` VARCHAR(45) NULL DEFAULT NULL,
  `Product_price` INT(11) NULL DEFAULT NULL,
  `Product_quantity` INT(11) NULL DEFAULT NULL,
  `Cart_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`LineItems_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `Order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` INT(11) NULL DEFAULT NULL,
  `Order_date` DATE NULL DEFAULT NULL,
  `Ship_date` DATE NULL DEFAULT NULL,
  `TotalPrice` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`order_lineitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_lineitems` (
  `Lineitems_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Product_id` VARCHAR(45) NOT NULL,
  `Product_price` FLOAT NULL DEFAULT NULL,
  `Shipment_status` VARCHAR(45) NULL DEFAULT NULL,
  `Order_id` INT(11) NULL DEFAULT NULL,
  `Product_quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Lineitems_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `payment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` INT(11) NOT NULL,
  `Card_number` VARCHAR(20) NULL DEFAULT NULL,
  `Card_cvv` VARCHAR(10) NULL DEFAULT NULL,
  `Card_expiry_month` VARCHAR(10) NULL DEFAULT NULL,
  `Card_expiry_year` VARCHAR(10) NULL DEFAULT NULL,
  `Zipcode` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `Product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL DEFAULT NULL,
  `Product_sku` VARCHAR(45) NULL DEFAULT NULL,
  `Product_name` VARCHAR(45) NULL DEFAULT NULL,
  `Product_desc` VARCHAR(150) NULL DEFAULT NULL,
  `Product_price` FLOAT NULL DEFAULT NULL,
  `Product_quantity` INT(11) NOT NULL,
  `subCategory_name` VARCHAR(45) NOT NULL,
  `filename` VARCHAR(50) NOT NULL,
  `filepath` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`salestax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salestax` (
  `Salestax_id` INT(11) NOT NULL AUTO_INCREMENT,
  `SalesTax_percentage` FLOAT NULL DEFAULT NULL,
  `SalesTax_zipcode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Salestax_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`securityquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`securityquestions` (
  `Customer_id` INT(11) NOT NULL DEFAULT '0',
  `Question_1` VARCHAR(50) NULL DEFAULT NULL,
  `Answer_1` VARCHAR(50) NULL DEFAULT NULL,
  `Question_2` VARCHAR(50) NULL DEFAULT NULL,
  `Answer_2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shipment` (
  `Shipment_id` INT(11) NOT NULL,
  `Customer_id` INT(11) NULL DEFAULT NULL,
  `Order_id` INT(11) NULL DEFAULT NULL,
  `Order_status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Shipment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`shiptoaddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shiptoaddress` (
  `Shiptoaddress_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` INT(11) NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Address1` VARCHAR(45) NULL DEFAULT NULL,
  `Address2` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `Mobilenumber` VARCHAR(50) NULL DEFAULT NULL,
  `Zipcode` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Shiptoaddress_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategory` (
  `subCategory_id` INT(11) NOT NULL AUTO_INCREMENT,
  `subCategory_name` VARCHAR(45) NOT NULL,
  `Category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subCategory_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `Subscription_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_id` INT(11) NOT NULL,
  `Frequency` INT(11) NOT NULL,
  `Expected_Deliverydate` DATE NOT NULL,
  `Timespan` INT(11) NOT NULL,
  `Product_id` INT(11) NOT NULL,
  `Quantity` INT(11) NOT NULL,
  `Order_CreationDate` DATETIME NOT NULL,
  PRIMARY KEY (`Subscription_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`testimagetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`testimagetable` (
  `idtestImageTable` INT(11) NOT NULL AUTO_INCREMENT,
  `image` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idtestImageTable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
